name: Custom CSS

on:
  push:
    branches:
      - main

jobs:
  custom-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create CSS file
        run: echo "body .gh a { display: none !important; }" > .github/hide-github.css

